version: '3'

services:
  web:
    environment:
    - APACHE_RUN_USER=#1000
    build:
      context: ./
    depends_on:
      - database
    ports:
    - 10000:80
    volumes:
    - webvol

  database:
    image: mariadb:10.4
    restart: on-failure
    ports:
    - 33061:3306
    environment:
      MARIADB_ROOT_PASSWORD: Admin@123
    volumes:
      - mysql
